name: appestacio
description: Aplicativo de controle de produção para indústria de canudinhos recheados

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  table_calendar: ^3.0.9

  # Persistência de dados
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Gráficos
  fl_chart: ^0.66.0

  # Internacionalização e datas
  intl: ^0.19.0

  # Gerenciamento de estado
  provider: ^6.0.5

  # Utilitários
  collection: ^1.17.2
  shared_preferences: ^2.2.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Geração de código
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  # Ícones do app
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "lib/assets/logo_foreground.png"
  adaptive_icon_background: "lib/assets/logo_background.png"
  adaptive_icon_foreground: "lib/assets/logo_foreground.png"